// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/Armor.h"
// HOLGEN_USER_DEFINED_BEGIN:Armor_CustomIncludes
#include <algorithm>
// HOLGEN_USER_DEFINED_END:Armor_CustomIncludes

namespace ex2_schemas {
void Armor::SetArmorClass(int8_t val) {
// HOLGEN_USER_DEFINED_BEGIN:Armor_SetArmorClass
  mArmorClass = std::clamp<int8_t>(val, -20, 20);
// HOLGEN_USER_DEFINED_END:Armor_SetArmorClass
}

void Armor::Initialize() {
// HOLGEN_USER_DEFINED_BEGIN:Armor_Initialize
  // It's a dirty way to assign ids. Data Managers can automate this!
  static uint32_t idCounter = 0x10000000;
  mId = idCounter++;
// HOLGEN_USER_DEFINED_END:Armor_Initialize
}

}
