// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/Weapon.h"
// HOLGEN_USER_DEFINED_BEGIN:Weapon_CustomIncludes
#include <cstdlib>
// HOLGEN_USER_DEFINED_END:Weapon_CustomIncludes

namespace ex2_schemas {
void Weapon::Initialize() {
// HOLGEN_USER_DEFINED_BEGIN:Weapon_Initialize
  static uint32_t idCounter = 0x20000000;
  mId = idCounter++;
// HOLGEN_USER_DEFINED_END:Weapon_Initialize
}

void Weapon::SetDamage(uint8_t min, uint8_t max) {
// HOLGEN_USER_DEFINED_BEGIN:Weapon_SetDamage
  // This is an invariant set by GetDamage.
  assert(min < max);
  mDamageMin = min;
  mDamageMax = max;
// HOLGEN_USER_DEFINED_END:Weapon_SetDamage
}

uint8_t Weapon::GetDamage() {
// HOLGEN_USER_DEFINED_BEGIN:Weapon_GetDamage
  // you'd probably come up with your own number generator in a real-life project, but rand() will do here.
  return mDamageMin + (rand() % (mDamageMax - mDamageMin));
// HOLGEN_USER_DEFINED_END:Weapon_GetDamage
}

}
