// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/Calculator.h"
// HOLGEN_USER_DEFINED_BEGIN:Calculator_CustomIncludes
// HOLGEN_USER_DEFINED_END:Calculator_CustomIncludes

namespace holgen_blackbox_test {
int64_t Calculator::SubtractThenMultiply(int64_t lhs, int64_t rhs) {
// HOLGEN_USER_DEFINED_BEGIN:Calculator_SubtractThenMultiply
  auto val = lhs - rhs;
  mCurVal.SetValue(mCurVal.GetValue() * val);
  return mCurVal.GetValue();
// HOLGEN_USER_DEFINED_END:Calculator_SubtractThenMultiply
}

}
