// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/Calculator.h"

namespace holgen_blackbox_test {
int64_t Calculator::SubtractThenMultiply(int64_t lhs, int64_t rhs) {
// HOLGEN_USER_DEFINED_BEGIN:Calculator_SubtractThenMultiply
// HOLGEN_USER_DEFINED_END:Calculator_SubtractThenMultiply
}
}
