// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestLuaStaticCppFunction.h"
// HOLGEN_USER_DEFINED_BEGIN:TestLuaStaticCppFunction_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestLuaStaticCppFunction_CustomIncludes

namespace holgen_blackbox_test {
TestLuaStaticCppFunction TestLuaStaticCppFunction::Factory(const uint32_t data) {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaStaticCppFunction_Factory
  TestLuaStaticCppFunction out;
  out.SetData(data);
  return out;
// HOLGEN_USER_DEFINED_END:TestLuaStaticCppFunction_Factory
}

}
