// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestLuaFuncTableWithSourceTable.h"
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableWithSourceTable_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableWithSourceTable_CustomIncludes

namespace holgen_blackbox_test {
void TestLuaFuncTableWithSourceTable::SetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableWithSourceTable_SetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableWithSourceTable_SetField_Const
}

int32_t TestLuaFuncTableWithSourceTable::GetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableWithSourceTable_GetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableWithSourceTable_GetField_Const
}

}
