// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestJsonTagManager.h"

namespace holgen_blackbox_test {
uint64_t TestJsonTagManager::GetOrInsert(const std::string& tag) {
// HOLGEN_USER_DEFINED_BEGIN:TestJsonTagManager_GetOrInsert
// HOLGEN_USER_DEFINED_END:TestJsonTagManager_GetOrInsert
}
}
