// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestLuaFuncTable.h"
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTable_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestLuaFuncTable_CustomIncludes

namespace holgen_blackbox_test {
void TestLuaFuncTable::SetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTable_SetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTable_SetField_Const
}

int32_t TestLuaFuncTable::GetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTable_GetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTable_GetField_Const
}

}
