// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestStructConstructor.h"
// HOLGEN_USER_DEFINED_BEGIN:TestStructConstructor_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestStructConstructor_CustomIncludes

namespace holgen_blackbox_test {
TestStructConstructor::TestStructConstructor(const float val)
// HOLGEN_USER_DEFINED_BEGIN:INITIALIZER_TestStructConstructor_Construct1
: mX(val), mY(val), mZ(val)
// HOLGEN_USER_DEFINED_END:INITIALIZER_TestStructConstructor_Construct1
{
// HOLGEN_USER_DEFINED_BEGIN:TestStructConstructor_Construct1
// HOLGEN_USER_DEFINED_END:TestStructConstructor_Construct1
}

TestStructConstructor::TestStructConstructor(const float x, const float y, const float z)
// HOLGEN_USER_DEFINED_BEGIN:INITIALIZER_TestStructConstructor_Construct3
: mX(x), mY(y), mZ(z)
// HOLGEN_USER_DEFINED_END:INITIALIZER_TestStructConstructor_Construct3
{
// HOLGEN_USER_DEFINED_BEGIN:TestStructConstructor_Construct3
// HOLGEN_USER_DEFINED_END:TestStructConstructor_Construct3
}

}
