// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestLuaFuncTableStatic.h"
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableStatic_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableStatic_CustomIncludes

namespace holgen_blackbox_test {
void TestLuaFuncTableStatic::SetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableStatic_SetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableStatic_SetField_Const
}

int32_t TestLuaFuncTableStatic::GetField(lua_State *luaState, const TestLuaFuncTableContainer *container) const {
// HOLGEN_USER_DEFINED_BEGIN:TestLuaFuncTableStatic_GetField_Const
// HOLGEN_USER_DEFINED_END:TestLuaFuncTableStatic_GetField_Const
}

}
