// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestJsonTag.h"
// HOLGEN_USER_DEFINED_BEGIN:TestJsonTag_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestJsonTag_CustomIncludes

namespace holgen_blackbox_test {
TestJsonTag::TestJsonTag(const uint64_t id, const std::string &name)
// HOLGEN_USER_DEFINED_BEGIN:INITIALIZER_TestJsonTag_Construct
    :
    mId(id), mName(name)
// HOLGEN_USER_DEFINED_END:INITIALIZER_TestJsonTag_Construct
{
// HOLGEN_USER_DEFINED_BEGIN:TestJsonTag_Construct
// HOLGEN_USER_DEFINED_END:TestJsonTag_Construct
}

}
