// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestJsonTagManager.h"
// HOLGEN_USER_DEFINED_BEGIN:TestJsonTagManager_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestJsonTagManager_CustomIncludes

namespace holgen_blackbox_test {
uint64_t TestJsonTagManager::GetOrInsert(const std::string& tag) {
// HOLGEN_USER_DEFINED_BEGIN:TestJsonTagManager_GetOrInsert
  auto tagPtr = GetTagFromName(tag);
  if (!tagPtr) {
    TestJsonTag tagObj;
    tagObj.SetName(tag);
    tagPtr = AddTag(std::move(tagObj));
  }
  return tagPtr->GetId();
// HOLGEN_USER_DEFINED_END:TestJsonTagManager_GetOrInsert
}
}
