// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestStructToString.h"
// HOLGEN_USER_DEFINED_BEGIN:TestStructToString_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestStructToString_CustomIncludes

namespace holgen_blackbox_test {
std::string TestStructToString::Stringify() const {
// HOLGEN_USER_DEFINED_BEGIN:TestStructToString_Stringify_Const
  return std::format("{},{}", mField1, mField2);
// HOLGEN_USER_DEFINED_END:TestStructToString_Stringify_Const
}

}
