// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestStructHashable.h"
// HOLGEN_USER_DEFINED_BEGIN:TestStructHashable_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestStructHashable_CustomIncludes

namespace holgen_blackbox_test {
uint64_t TestStructHashable::Hash() const {
// HOLGEN_USER_DEFINED_BEGIN:TestStructHashable_Hash_Const
  return uint64_t(mField1) << 32 | uint64_t(mField2);
// HOLGEN_USER_DEFINED_END:TestStructHashable_Hash_Const
}

}
