// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/TestStructVirtualMethods.h"
// HOLGEN_USER_DEFINED_BEGIN:TestStructVirtualMethods_CustomIncludes
// HOLGEN_USER_DEFINED_END:TestStructVirtualMethods_CustomIncludes

namespace holgen_blackbox_test {
uint32_t TestStructVirtualMethods::VirtualFunc() {
// HOLGEN_USER_DEFINED_BEGIN:TestStructVirtualMethods_VirtualFunc
  return 42;
// HOLGEN_USER_DEFINED_END:TestStructVirtualMethods_VirtualFunc
}

}
