// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/Weapon.h"

namespace holgen_blackbox_test {
uint32_t Weapon::GetAverageDamage() {
// HOLGEN_USER_DEFINED_BEGIN:Weapon_GetAverageDamage
// HOLGEN_USER_DEFINED_END:Weapon_GetAverageDamage
}
}
