-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Character
---@field id number
---@field name string
---@field race Race
---@field armor Armor
Character = {}
