-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class ArmorMeta
---@field id number
---@field name string
---@field alternativeName string
---@field armorClass number
ArmorMeta = {}
