-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Calculator
---@field curVal Number
Calculator = {}

---@param val number
---@return number
function Calculator:Add(val) end

---@param val Number
---@return Number
function Calculator:Subtract(val) end
---@type table<string, fun(self: Calculator, val: Number): Number>
Ops = nil

---@param lhs number
---@param rhs number
---@return number
function Calculator:SubtractThenMultiply(lhs, rhs) end
