-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class CharacterMeta
---@field id number
---@field name string
---@field bootId number
---@field boot BootMeta
---@field armorId number
---@field armor ArmorMeta
CharacterMeta = {}
