-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Character
---@field id number
---@field name string
---@field bootId number
---@field boot Boot
---@field armorId number
---@field armor Armor
Character = {}
