-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class CountryMeta
---@field leader PersonMeta
---@field citizens PersonMeta[]
---@field population table<number, number>
CountryMeta = {}
