-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Country
---@field leader Person
---@field citizens Person[]
---@field population table<number, number>
Country = {}
