-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class DamageMultiplierMeta
---@field when string
---@field value number
DamageMultiplierMeta = {}
