-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class GameData
---@field boots Boot[]
---@field armors Armor[]
---@field characters Character[]
GameData = {}

---@param key string
---@return Boot
function GameData:GetBootFromName(key) end

---@param key string
---@return Armor
function GameData:GetArmorFromName(key) end

---@param key string
---@return Armor
function GameData:GetArmorFromAlternativeName(key) end

---@param key string
---@return Character
function GameData:GetCharacterFromName(key) end

---@param elem Boot
---@return Boot
function GameData:AddBoot(elem) end

---@param elem Armor
---@return Armor
function GameData:AddArmor(elem) end

---@param elem Character
---@return Character
function GameData:AddCharacter(elem) end

---@param idx number
---@return Boot
function GameData:GetBoot(idx) end

---@param idx number
---@return Armor
function GameData:GetArmor(idx) end

---@param idx number
---@return Character
function GameData:GetCharacter(idx) end

---@param idx number
function GameData:DeleteBoot(idx) end

---@param idx number
function GameData:DeleteArmor(idx) end

---@param idx number
function GameData:DeleteCharacter(idx) end

---@return number
function GameData:GetBootCount() end

---@return number
function GameData:GetArmorCount() end

---@return number
function GameData:GetCharacterCount() end
