-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class GameDataMeta
---@field boots BootMeta[]
---@field armors ArmorMeta[]
---@field characters CharacterMeta[]
GameDataMeta = {}

---@param key string
---@return BootMeta
function GameDataMeta:GetBootFromName(key) end

---@param elem BootMeta
---@return BootMeta
function GameDataMeta:AddBoot(elem) end

---@param idx number
---@return BootMeta
function GameDataMeta:GetBoot(idx) end

---@return number
function GameDataMeta:GetBootCount() end

---@param key string
---@return ArmorMeta
function GameDataMeta:GetArmorFromName(key) end

---@param key string
---@return ArmorMeta
function GameDataMeta:GetArmorFromAlternativeName(key) end

---@param elem ArmorMeta
---@return ArmorMeta
function GameDataMeta:AddArmor(elem) end

---@param idx number
---@return ArmorMeta
function GameDataMeta:GetArmor(idx) end

---@return number
function GameDataMeta:GetArmorCount() end

---@param key string
---@return CharacterMeta
function GameDataMeta:GetCharacterFromName(key) end

---@param elem CharacterMeta
---@return CharacterMeta
function GameDataMeta:AddCharacter(elem) end

---@param idx number
---@return CharacterMeta
function GameDataMeta:GetCharacter(idx) end

---@return number
function GameDataMeta:GetCharacterCount() end
