-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class HumanManager
---@field humans table<number, Human>
HumanManager = {}

---@param key string
---@return Human
function HumanManager:GetHumanFromName(key) end

---@param elem Human
---@return Human
function HumanManager:AddHuman(elem) end

---@param idx number
---@return Human
function HumanManager:GetHuman(idx) end

---@param key number
---@return boolean
function HumanManager:HasHuman(key) end

---@param key number
function HumanManager:DeleteHuman(key) end

---@return number
function HumanManager:GetHumanCount() end
