-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class LuaTestStructContainer
---@field testVector number[]
---@field testMap table<string, number>
LuaTestStructContainer = {}

---@param elem number
---@return number
function LuaTestStructContainer:AddTestVectorElem(elem) end

---@param idx number
---@return number
function LuaTestStructContainer:GetTestVectorElem(idx) end

---@param idx number
function LuaTestStructContainer:DeleteTestVectorElem(idx) end

---@return number
function LuaTestStructContainer:GetTestVectorElemCount() end
