-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class PersonMeta
---@field race number
---@field currentCountry number
---@field currentCity number
---@field homeCountry number
---@field placeOfBirth number
PersonMeta = {}
