-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class RaceMeta
---@field id number
---@field name string
---@field hairColors string[]
---@field names table<string, string[]>
RaceMeta = {}
