-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestJsonStructMapWithConverters
---@field testMapConvertElem table<string, number>
---@field testMapConvertKey table<number, string>
---@field testMapConvertKeyElem table<number, number>
TestJsonStructMapWithConverters = {}
