-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerMapMeta
---@field innerStructsWithId table<number, TestContainerInnerStructWithIdMeta>
TestContainerMapMeta = {}

---@param key string
---@return TestContainerInnerStructWithIdMeta
function TestContainerMapMeta:GetInnerStructWithIdFromName(key) end

---@param elem TestContainerInnerStructWithIdMeta
---@return TestContainerInnerStructWithIdMeta
function TestContainerMapMeta:AddInnerStructWithId(elem) end

---@param idx number
---@return TestContainerInnerStructWithIdMeta
function TestContainerMapMeta:GetInnerStructWithId(idx) end

---@param key number
---@return bool
function TestContainerMapMeta:HasInnerStructWithId(key) end

---@param key number
function TestContainerMapMeta:DeleteInnerStructWithId(key) end

---@return number
function TestContainerMapMeta:GetInnerStructWithIdCount() end
