-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestCompositeIdObjectType 0|1|2
TestCompositeIdObjectType = {
  Human = 0,
  Cat = 1,
  Dog = 2,
  Invalid = 3,
}
