-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestBitmapStructMeta
---@field bitmapField TestBitmap
TestBitmapStructMeta = {}

---@param val number
---@return bool
function TestBitmapStructMeta:HasBitmapField(val) end

---@param val number
function TestBitmapStructMeta:AddBitmapField(val) end

---@param val number
function TestBitmapStructMeta:RemoveBitmapField(val) end

---@param val number
function TestBitmapStructMeta:ToggleBitmapField(val) end
