-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerSet
---@field stringContainer string[]
---@field unsignedContainer number[]
TestContainerSet = {}

---@param elem string
---@return string
function TestContainerSet:AddStringElem(elem) end

---@param elem number
---@return number
function TestContainerSet:AddUnsignedElem(elem) end

---@param elem string
function TestContainerSet:DeleteStringElem(elem) end

---@param elem number
function TestContainerSet:DeleteUnsignedElem(elem) end

---@param elem string
---@return boolean
function TestContainerSet:HasStringElem(elem) end

---@return number
function TestContainerSet:GetStringElemCount() end

---@param elem number
---@return boolean
function TestContainerSet:HasUnsignedElem(elem) end

---@return number
function TestContainerSet:GetUnsignedElemCount() end
