-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerEnum
---@field skills number[]
TestContainerEnum = {}

---@param idx TestContainerSkill
---@return number
function TestContainerEnum:GetSkill(idx) end

---@return number
function TestContainerEnum:GetSkillCount() end
