-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructHuman
---@field name string
---@field nationality string
TestVariantStructHuman = {}
