-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerMap
---@field innerStructsWithId table<number, TestContainerInnerStructWithId>
TestContainerMap = {}

---@param key string
---@return TestContainerInnerStructWithId
function TestContainerMap:GetInnerStructWithIdFromName(key) end

---@param elem TestContainerInnerStructWithId
---@return TestContainerInnerStructWithId
function TestContainerMap:AddInnerStructWithId(elem) end

---@param idx number
---@return TestContainerInnerStructWithId
function TestContainerMap:GetInnerStructWithId(idx) end

---@param key number
function TestContainerMap:DeleteInnerStructWithId(key) end

---@param key number
---@return boolean
function TestContainerMap:HasInnerStructWithId(key) end

---@return number
function TestContainerMap:GetInnerStructWithIdCount() end
