-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestJsonStructContainer
---@field tags TestJsonTag[]
---@field enums TestJsonEnum[]
---@field tagMap table<string, TestJsonTag>
TestJsonStructContainer = {}
