-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestEnumProperty 0|1|2
TestEnumProperty = {
  Human = 0,
  Elf = 1,
  Goblin = 2,
  Invalid = 3,
}
