-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestEventListener
---@field name string
---@field OnEvent1 fun(self: TestEventListener, val: number)
---@field OnEvent2 fun(self: TestEventListener): number
---@field TABLE string
TestEventListener = {}
