-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaStaticCppFunction
---@field data number
TestLuaStaticCppFunction = {}

---@param data number
---@return TestLuaStaticCppFunction
function TestLuaStaticCppFunction.Factory(data) end
