-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestBitmap 1|2|4|8|16
TestBitmap = {
  Entry1 = 1,
  Entry2 = 2,
  Entry3 = 4,
  Entry4 = 8,
  Entry5 = 16,
  Entry1Index = 0,
  Entry2Index = 1,
  Entry3Index = 2,
  Entry4Index = 3,
  Entry5Index = 4,
}
