-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructComparable
---@field field1 number
---@field field2 number
TestStructComparable = {}
