-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTable
---@field SetField fun(self: TestLuaFuncTable, container: TestLuaFuncTableContainer)
---@field GetField fun(self: TestLuaFuncTable, container: TestLuaFuncTableContainer): number
---@field TABLE string
TestLuaFuncTable = {}
