-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestBitmapStruct
---@field bitmapField TestBitmap
TestBitmapStruct = {}

---@param val number
---@return boolean
function TestBitmapStruct:HasBitmapField(val) end

---@param val number
function TestBitmapStruct:AddBitmapField(val) end

---@param val number
function TestBitmapStruct:RemoveBitmapField(val) end

---@param val number
function TestBitmapStruct:ToggleBitmapField(val) end
