-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructVirtualMethodsMeta
TestStructVirtualMethodsMeta = {}

---@return number
function TestStructVirtualMethodsMeta:VirtualFunc() end

---@return number
function TestStructVirtualMethodsMeta:PureVirtualFunc() end
