-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdContainer
---@field humans TestCompositeIdHuman[]
TestCompositeIdContainer = {}

---@param key string
---@return TestCompositeIdHuman
function TestCompositeIdContainer:GetHumanFromName(key) end

---@param elem TestCompositeIdHuman
---@return TestCompositeIdHuman
function TestCompositeIdContainer:AddHuman(elem) end

---@param idx number
---@return TestCompositeIdHuman
function TestCompositeIdContainer:GetHuman(idx) end

---@param idx number
function TestCompositeIdContainer:DeleteHuman(idx) end

---@return number
function TestCompositeIdContainer:GetHumanCount() end
