-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdCompositeId
---@field type TestCompositeIdObjectType
---@field version number
---@field id number
TestCompositeIdCompositeId = {}
