-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestJsonTagManager
---@field tags TestJsonTag[]
TestJsonTagManager = {}

---@param tag string
---@return number
function TestJsonTagManager:GetOrInsert(tag) end

---@param key string
---@return TestJsonTag
function TestJsonTagManager:GetTagFromName(key) end

---@param elem TestJsonTag
---@return TestJsonTag
function TestJsonTagManager:AddTag(elem) end

---@param idx number
---@return TestJsonTag
function TestJsonTagManager:GetTag(idx) end

---@param idx number
function TestJsonTagManager:DeleteTag(idx) end

---@return number
function TestJsonTagManager:GetTagCount() end
