-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructArrayMeta
---@field type TestStructArrayType
TestStructArrayMeta = {}

---@return TestStructArrayCustomData1Meta
function TestStructArrayMeta:GetData1() end

---@return TestStructArrayCustomData2Meta
function TestStructArrayMeta:GetData2() end
