-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdDog
---@field id number
---@field version number
---@field breed string
TestCompositeIdDog = {}
