-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestJsonTagManagerMeta
---@field tags TestJsonTagMeta[]
TestJsonTagManagerMeta = {}

---@param tag string
---@return number
function TestJsonTagManagerMeta:GetOrInsert(tag) end

---@param key string
---@return TestJsonTagMeta
function TestJsonTagManagerMeta:GetTagFromName(key) end

---@param elem TestJsonTagMeta
---@return TestJsonTagMeta
function TestJsonTagManagerMeta:AddTag(elem) end

---@param idx number
---@return TestJsonTagMeta
function TestJsonTagManagerMeta:GetTag(idx) end

---@return number
function TestJsonTagManagerMeta:GetTagCount() end
