-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructHashableMapMeta
---@field data table<TestStructHashableMeta, string>
TestStructHashableMapMeta = {}
