-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructDifferentTypes
---@field being1 number[]
---@field being2 number[]
TestVariantStructDifferentTypes = {}

function TestVariantStructDifferentTypes:ResetBeing1Type() end

function TestVariantStructDifferentTypes:ResetBeing2Type() end
