-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerVectorMeta
---@field innerStructsWithId TestContainerInnerStructWithIdMeta[]
---@field innerStructsNoId TestContainerInnerStructNoIdMeta[]
---@field stringContainer string[]
---@field unsignedContainer number[]
TestContainerVectorMeta = {}

---@param key string
---@return TestContainerInnerStructWithIdMeta
function TestContainerVectorMeta:GetInnerStructWithIdFromName(key) end

---@param elem TestContainerInnerStructWithIdMeta
---@return TestContainerInnerStructWithIdMeta
function TestContainerVectorMeta:AddInnerStructWithId(elem) end

---@param idx number
---@return TestContainerInnerStructWithIdMeta
function TestContainerVectorMeta:GetInnerStructWithId(idx) end

---@return number
function TestContainerVectorMeta:GetInnerStructWithIdCount() end

---@param key string
---@return TestContainerInnerStructNoIdMeta
function TestContainerVectorMeta:GetInnerStructNoIdFromName(key) end

---@param elem TestContainerInnerStructNoIdMeta
---@return TestContainerInnerStructNoIdMeta
function TestContainerVectorMeta:AddInnerStructNoId(elem) end

---@param idx number
---@return TestContainerInnerStructNoIdMeta
function TestContainerVectorMeta:GetInnerStructNoId(idx) end

---@param idx number
function TestContainerVectorMeta:DeleteInnerStructNoId(idx) end

---@return number
function TestContainerVectorMeta:GetInnerStructNoIdCount() end

---@param elem string
---@return string
function TestContainerVectorMeta:AddStringElem(elem) end

---@param idx number
---@return string
function TestContainerVectorMeta:GetStringElem(idx) end

---@param idx number
function TestContainerVectorMeta:DeleteStringElem(idx) end

---@return number
function TestContainerVectorMeta:GetStringElemCount() end

---@param elem number
---@return number
function TestContainerVectorMeta:AddUnsignedElem(elem) end

---@param idx number
---@return number
function TestContainerVectorMeta:GetUnsignedElem(idx) end

---@param idx number
function TestContainerVectorMeta:DeleteUnsignedElem(idx) end

---@return number
function TestContainerVectorMeta:GetUnsignedElemCount() end
