-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructComparableMapMeta
---@field data table<TestStructComparableMeta, string>
TestStructComparableMapMeta = {}
