-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructHashable
---@field field1 number
---@field field2 number
TestStructHashable = {}

---@return number
function TestStructHashable:Hash() end
