-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestEnumDefaultValue 0|1|2
TestEnumDefaultValue = {
  SomeEntry = 0,
  DefaultEntry = 1,
  AnotherEntry = 2,
  Invalid = 3,
}
