-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerSetMeta
---@field stringContainer string[]
---@field unsignedContainer number[]
TestContainerSetMeta = {}

---@param elem string
---@return string
function TestContainerSetMeta:AddStringElem(elem) end

---@param elem string
---@return bool
function TestContainerSetMeta:HasStringElem(elem) end

---@param elem string
function TestContainerSetMeta:DeleteStringElem(elem) end

---@return number
function TestContainerSetMeta:GetStringElemCount() end

---@param elem number
---@return number
function TestContainerSetMeta:AddUnsignedElem(elem) end

---@param elem number
---@return bool
function TestContainerSetMeta:HasUnsignedElem(elem) end

---@param elem number
function TestContainerSetMeta:DeleteUnsignedElem(elem) end

---@return number
function TestContainerSetMeta:GetUnsignedElemCount() end
