-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestEnumStruct
---@field enumField TestEnum
---@field enumDefaultValueField TestEnumDefaultValue
TestEnumStruct = {}
