-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestContainerSkill 0|1|2|3
TestContainerSkill = {
  Strength = 0,
  Perception = 1,
  Endurance = 2,
  Charisma = 3,
  Invalid = 4,
}
