-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructSmartPointers
---@field sharedPtr any
---@field sharedPtrs any[]
---@field uniquePtr any
---@field uniquePtrs any[]
TestStructSmartPointers = {}
