-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerInnerStructNoId
---@field field number
---@field name string
TestContainerInnerStructNoId = {}
