-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdHuman
---@field id number
---@field version number
TestCompositeIdHuman = {}
