-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructArrayCustomData2
---@field f1 number
---@field f2 number
---@field f3 number
TestStructArrayCustomData2 = {}
