-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructCat
---@field name string
---@field color string
TestVariantStructCat = {}
