-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaCalculator
---@field lastValue TestLuaNumber
TestLuaCalculator = {}

---@param num number
---@return number
function TestLuaCalculator:AddPrimitive(num) end

---@param num TestLuaNumber
---@return number
function TestLuaCalculator:AddRef(num) end

---@param num TestLuaNumber
---@return number
function TestLuaCalculator:AddNullable(num) end

---@param num number
---@return TestLuaNumber
function TestLuaCalculator:ReturnNullable(num) end

---@param num number
---@return TestLuaNumber
function TestLuaCalculator:ReturnRef(num) end

---@param num number
---@return TestLuaNumber
function TestLuaCalculator:ReturnNew(num) end
