-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTableMeta
TestLuaFuncTableMeta = {}

---@param container TestLuaFuncTableContainerMeta
function TestLuaFuncTableMeta:SetField(container) end

---@param container TestLuaFuncTableContainerMeta
---@return number
function TestLuaFuncTableMeta:GetField(container) end
