-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructSmartPointersMeta
---@field sharedPtr any
---@field sharedPtrs any[]
---@field uniquePtr any
---@field uniquePtrs any[]
TestStructSmartPointersMeta = {}
