-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructArray
---@field type TestStructArrayType
TestStructArray = {}

---@return TestStructArrayCustomData1
function TestStructArray:GetData1() end

---@return TestStructArrayCustomData2
function TestStructArray:GetData2() end
