-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructHumanMeta
---@field name string
---@field nationality string
TestVariantStructHumanMeta = {}
