-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructHashableMeta
---@field field1 number
---@field field2 number
TestStructHashableMeta = {}

---@return number
function TestStructHashableMeta:Hash() end
