-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructComparableMeta
---@field field1 number
---@field field2 number
TestStructComparableMeta = {}
