-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTableWithSourceTable
---@field SetField fun(self: TestLuaFuncTableWithSourceTable, container: TestLuaFuncTableContainer)
---@field GetField fun(self: TestLuaFuncTableWithSourceTable, container: TestLuaFuncTableContainer): number
---@field TABLE string
TestLuaFuncTableWithSourceTable = {}

---@type table<string, TestLuaFuncTableWithSourceTable>
Scripts = nil
