-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructVirtualMethods
TestStructVirtualMethods = {}

---@return number
function TestStructVirtualMethods:VirtualFunc() end

---@return number
function TestStructVirtualMethods:PureVirtualFunc() end
