-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructArrayMeta
---@field type TestStructArrayType
---@field customData number[]
TestStructArrayMeta = {}

---@param type TestStructArrayType
function TestStructArrayMeta:Initialize(type) end

---@return TestStructArrayCustomData1Meta
function TestStructArrayMeta:GetData1() end

---@return TestStructArrayCustomData2Meta
function TestStructArrayMeta:GetData2() end
