-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestVariantStructType 0|1
TestVariantStructType = {
  Human = 0,
  Cat = 1,
  Invalid = 2,
}
