-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestStructArrayType 0|1
TestStructArrayType = {
  Type1 = 0,
  Type2 = 1,
  Invalid = 2,
}
