-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructToStringMeta
---@field field1 string
---@field field2 string
TestStructToStringMeta = {}

---@return string
function TestStructToStringMeta:Stringify() end
