-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructCatMeta
---@field name string
---@field color string
TestVariantStructCatMeta = {}
