-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestEnumStructMeta
---@field enumField TestEnum
---@field enumDefaultValueField TestEnumDefaultValue
TestEnumStructMeta = {}
