-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaRegistryDataMeta
---@field data any
TestLuaRegistryDataMeta = {}

---@param initData any
function TestLuaRegistryDataMeta:Init(initData) end

---@return number
function TestLuaRegistryDataMeta:Get() end

---@param val number
function TestLuaRegistryDataMeta:Add(val) end
