-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaRegistryData
---@field data any
---@field Init fun(self: TestLuaRegistryData, initData: any)
---@field Get fun(self: TestLuaRegistryData): number
---@field Add fun(self: TestLuaRegistryData, val: number)
---@field TABLE string
TestLuaRegistryData = {}
