-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructExplicitTypeMeta
---@field type TestVariantStructType
---@field being1 number[]
---@field being2 number[]
TestVariantStructExplicitTypeMeta = {}
