-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructSingleElemWithId
---@field id number
---@field name string
TestStructSingleElemWithId = {}
