-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerEnumMeta
---@field skills number[]
TestContainerEnumMeta = {}

---@param idx TestContainerSkill
---@return number
function TestContainerEnumMeta:GetSkill(idx) end

---@return number
function TestContainerEnumMeta:GetSkillCount() end
