-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestContainerInnerStructWithId
---@field id number
---@field name string
TestContainerInnerStructWithId = {}
