-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTableStaticMeta
TestLuaFuncTableStaticMeta = {}

---@param container TestLuaFuncTableContainerMeta
function TestLuaFuncTableStaticMeta:SetField(container) end

---@param container TestLuaFuncTableContainerMeta
---@return number
function TestLuaFuncTableStaticMeta:GetField(container) end
