-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaCalculatorMeta
---@field lastValue TestLuaNumberMeta
TestLuaCalculatorMeta = {}

---@param num number
---@return number
function TestLuaCalculatorMeta:AddPrimitive(num) end

---@param num TestLuaNumberMeta
---@return number
function TestLuaCalculatorMeta:AddRef(num) end

---@param num TestLuaNumberMeta
---@return number
function TestLuaCalculatorMeta:AddNullable(num) end

---@param num number
---@return TestLuaNumberMeta
function TestLuaCalculatorMeta:ReturnNullable(num) end

---@param num number
---@return TestLuaNumberMeta
function TestLuaCalculatorMeta:ReturnRef(num) end

---@param num number
---@return TestLuaNumberMeta
function TestLuaCalculatorMeta:ReturnNew(num) end
