-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructComparableMap
---@field data table<TestStructComparable, string>
TestStructComparableMap = {}
