-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStruct
---@field testFieldBool boolean
---@field testFieldUnsigned number
---@field testFieldString string
---@field testFieldUserdata userdata
TestStruct = {}
