-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTableWithSourceTableMeta
TestLuaFuncTableWithSourceTableMeta = {}

---@param container TestLuaFuncTableContainerMeta
function TestLuaFuncTableWithSourceTableMeta:SetField(container) end

---@param container TestLuaFuncTableContainerMeta
---@return number
function TestLuaFuncTableWithSourceTableMeta:GetField(container) end

---@type table<string, TestLuaFuncTableWithSourceTableMeta>
Scripts = nil
