-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructDifferentTypesMeta
---@field being1 number[]
---@field being2 number[]
TestVariantStructDifferentTypesMeta = {}
