-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructPairFields
---@field intStringPair {number, string}
---@field pairVector {string, number}[]
TestStructPairFields = {}
