-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructConstructorMeta
---@field x number
---@field y number
---@field z number
TestStructConstructorMeta = {}

---@param val number
---@return TestStructConstructorMeta
function TestStructConstructorMeta.Construct1(val) end

---@param x number
---@param y number
---@param z number
---@return TestStructConstructorMeta
function TestStructConstructorMeta.Construct3(x, y, z) end
