-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructSingleElemContainer
---@field singleElemStructs TestStructSingleElem[]
---@field singleElemStructsWithId TestStructSingleElemWithId[]
TestStructSingleElemContainer = {}

---@param elem TestStructSingleElem
---@return TestStructSingleElem
function TestStructSingleElemContainer:AddSingleElemStruct(elem) end

---@param elem TestStructSingleElemWithId
---@return TestStructSingleElemWithId
function TestStructSingleElemContainer:AddSingleElemStructWithId(elem) end

---@param idx number
---@return TestStructSingleElem
function TestStructSingleElemContainer:GetSingleElemStruct(idx) end

---@param idx number
function TestStructSingleElemContainer:DeleteSingleElemStruct(idx) end

---@return number
function TestStructSingleElemContainer:GetSingleElemStructCount() end

---@param idx number
---@return TestStructSingleElemWithId
function TestStructSingleElemContainer:GetSingleElemStructWithId(idx) end

---@return number
function TestStructSingleElemContainer:GetSingleElemStructWithIdCount() end
