-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestJsonTag
---@field id number
---@field name string
TestJsonTag = {}

---@param id number
---@param name string
---@return TestJsonTag
function TestJsonTag.Construct(id, name) end
