-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructConstructor
---@field x number
---@field y number
---@field z number
TestStructConstructor = {}

---@param val number
---@return TestStructConstructor
function TestStructConstructor.Construct1(val) end

---@param x number
---@param y number
---@param z number
---@return TestStructConstructor
function TestStructConstructor.Construct3(x, y, z) end
