-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdCat
---@field id number
---@field version number
---@field name string
---@field breed string
TestCompositeIdCat = {}

---@return TestCompositeIdCompositeId
function TestCompositeIdCat:GetCompositeId() end

---@return boolean
function TestCompositeIdCat:IsValid() end
