-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias TestJsonEnum 1|2|5
TestJsonEnum = {
  Entry1 = 1,
  Entry2 = 2,
  Entry5 = 5,
  Invalid = 0,
}
