-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructMeta
---@field testFieldBool bool
---@field testFieldUnsigned number
---@field testFieldString string
---@field testFieldUserdata userdata
TestStructMeta = {}
