-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructToString
---@field field1 string
---@field field2 string
TestStructToString = {}

---@return string
function TestStructToString:Stringify() end
