-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaStaticCppFunctionMeta
---@field data number
TestLuaStaticCppFunctionMeta = {}

---@param data number
---@return TestLuaStaticCppFunctionMeta
function TestLuaStaticCppFunctionMeta.Factory(data) end
