-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructHashableMap
---@field data table<TestStructHashable, string>
TestStructHashableMap = {}
