-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestLuaFuncTableStatic
---@field SetField fun(container: TestLuaFuncTableContainer)
---@field GetField fun(container: TestLuaFuncTableContainer): number
---@field TABLE string
TestLuaFuncTableStatic = {}
