-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestCompositeIdHuman
---@field id number
---@field version number
---@field name string
TestCompositeIdHuman = {}

---@return TestCompositeIdCompositeId
function TestCompositeIdHuman:GetCompositeId() end

---@return boolean
function TestCompositeIdHuman:IsValid() end
