-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructExplicitType
---@field type TestVariantStructType
---@field being1 number[]
---@field being2 number[]
TestVariantStructExplicitType = {}
