-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestVariantStructSharedType
---@field being1 number[]
---@field being2 number[]
TestVariantStructSharedType = {}

function TestVariantStructSharedType:ResetBeingType() end
