-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class TestStructSingleElemWithIdMeta
---@field id number
---@field name string
TestStructSingleElemWithIdMeta = {}
