-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Weapon
---@field damageMin number
---@field damageMax number
---@field damageMultipliers DamageMultiplier[]
---@field modifiers string[]
Weapon = {}

---@return number
function Weapon:GetAverageDamage() end
