-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class WeaponMeta
---@field damageMin number
---@field damageMax number
---@field damageMultipliers DamageMultiplierMeta[]
---@field modifiers string[]
WeaponMeta = {}

---@return number
function WeaponMeta:GetAverageDamage() end
