// This file is partially generated by holgen. Only modify the custom sections.
#include "../gen/CounterManager.h"
// HOLGEN_USER_DEFINED_BEGIN:CounterManager_CustomIncludes
// HOLGEN_USER_DEFINED_END:CounterManager_CustomIncludes

namespace holgen_blackbox_csharp {
Counter &CounterManager::GetCounter(const std::string &name) {
// HOLGEN_USER_DEFINED_BEGIN:CounterManager_GetCounter
  auto it = mCounters.find(name);
  if (it == mCounters.end()) {
    it = mCounters.try_emplace(name, Counter{}).first;
  }
  return it->second;
// HOLGEN_USER_DEFINED_END:CounterManager_GetCounter
}

Counter *CounterManager::GetCounterPtr(const std::string &name) {
// HOLGEN_USER_DEFINED_BEGIN:CounterManager_GetCounterPtr
  return &GetCounter(name);
// HOLGEN_USER_DEFINED_END:CounterManager_GetCounterPtr
}

void CounterManager::InsertCounterBumper(ICounterBumper bumper) {
// HOLGEN_USER_DEFINED_BEGIN:CounterManager_InsertCounterBumper
  mCounterBumpers.push_back(std::move(bumper));
// HOLGEN_USER_DEFINED_END:CounterManager_InsertCounterBumper
}

}
