// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public class CounterManager
{
  public static Counter GetCounter(string name)
  {
    return new Counter(Marshal.GetDelegateForFunctionPointer<CounterManagerGetCounterDelegate>(_getCounterImpl)(name));
  }
  public static Counter GetCounterPtr(string name)
  {
    return new Counter(Marshal.GetDelegateForFunctionPointer<CounterManagerGetCounterPtrDelegate>(_getCounterPtrImpl)(name));
  }
  public static void HolgenInitialize(CounterManagerGetCounterDelegate counterManagerGetCounterDelegate, CounterManagerGetCounterPtrDelegate counterManagerGetCounterPtrDelegate)
  {
    _getCounterImpl = Marshal.GetFunctionPointerForDelegate(counterManagerGetCounterDelegate);
    _getCounterPtrImpl = Marshal.GetFunctionPointerForDelegate(counterManagerGetCounterPtrDelegate);
  }
  
  public delegate IntPtr CounterManagerGetCounterDelegate(string name);
  public delegate IntPtr CounterManagerGetCounterPtrDelegate(string name);
  public delegate void CounterManagerHolgenInitializeDelegate(CounterManagerGetCounterDelegate counterManagerGetCounterDelegate, CounterManagerGetCounterPtrDelegate counterManagerGetCounterPtrDelegate);
  
  private static IntPtr _getCounterImpl = IntPtr.Zero;
  private static IntPtr _getCounterPtrImpl = IntPtr.Zero;
  
}
