// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

internal static class DeferredDeleter
{
  public static void Perform(IntPtr ptr)
  {
    Marshal.GetDelegateForFunctionPointer<DeferredDeleterPerformDelegate>(_performImpl)(ptr);
  }
  public static void HolgenInitialize(DeferredDeleterPerformDelegate deferredDeleterPerformDelegate)
  {
    _performImpl = Marshal.GetFunctionPointerForDelegate(deferredDeleterPerformDelegate);
  }
  
  public delegate void DeferredDeleterPerformDelegate(IntPtr ptr);
  public delegate void DeferredDeleterHolgenInitializeDelegate(DeferredDeleterPerformDelegate deferredDeleterPerformDelegate);
  
  private static IntPtr _performImpl = IntPtr.Zero;
  
}
