// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public class HolgenDotNetInterface
{
  public static void HolgenFree(IntPtr ptr)
  {
    var handle = GCHandle.FromIntPtr(ptr);
    handle.Free();
  }
  
  public delegate void HolgenDotNetInterfaceHolgenFreeDelegate(IntPtr ptr);
  
}
