// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public abstract class ICounterBumper
{
  public IntPtr HolgenPtr
  {
    get
    {
      if (!_holgenPtr.IsAllocated)
      {
        _holgenPtr = GCHandle.Alloc(this);
      }
      return (IntPtr)_holgenPtr;
    }
  }
  
  public abstract void SetName(string name);
  public static void SetNameCaller(IntPtr holgenObject, string name)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetName(name);
  }
  public abstract string GetName();
  public static string GetNameCaller(IntPtr holgenObject)
  {
    return ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).GetName();
  }
  public abstract void Bump();
  public static void BumpCaller(IntPtr holgenObject)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).Bump();
  }
  public abstract void SetNameFromCounter(Counter ctr);
  public static void SetNameFromCounterCaller(IntPtr holgenObject, IntPtr ctr)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetNameFromCounter(new Counter(ctr));
  }
  public abstract void SetNameFromRevision(ModuleVersion version);
  public static void SetNameFromRevisionCaller(IntPtr holgenObject, ref ModuleVersion.Fields version)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetNameFromRevision(new ModuleVersion{Data = version});
  }
  public abstract ModuleVersion GetVersion();
  public static ModuleVersion.Fields GetVersionCaller(IntPtr holgenObject)
  {
    return ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).GetVersion().Data;
  }
  public abstract Counter GetCounter();
  public static IntPtr GetCounterCaller(IntPtr holgenObject)
  {
    return ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).GetCounter().HolgenPtr;
  }
  public abstract ICounterBumper Clone();
  public static IntPtr CloneCaller(IntPtr holgenObject)
  {
    return ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).Clone().HolgenPtr;
  }
  public abstract void CopyFrom(ICounterBumper other);
  public static void CopyFromCaller(IntPtr holgenObject, IntPtr other)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).CopyFrom(((ICounterBumper)GCHandle.FromIntPtr(other).Target!));
  }
  public abstract void BumpMultiple(string[] names, uint[] counts);
  public static void BumpMultipleCaller(IntPtr holgenObject, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex=2)] string[] names, ulong namesHolgenSize, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex=4)] uint[] counts, ulong countsHolgenSize)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).BumpMultiple(names, counts);
  }
  public abstract void SetNameConcatArray(string[] name);
  public static void SetNameConcatArrayCaller(IntPtr holgenObject, [MarshalAs(UnmanagedType.LPArray, SizeConst=3)] string[] name)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetNameConcatArray(name);
  }
  public abstract int[] SplitNameAndParseSigned(sbyte delim);
  public static IntPtr SplitNameAndParseSignedCaller(IntPtr holgenObject, sbyte delim, out ulong holgenReturnValueHolgenSize)
  {
    var holgenResult = ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SplitNameAndParseSigned(delim);
    holgenReturnValueHolgenSize = (ulong)holgenResult.Length;
    IntPtr holgenReturnValue = Marshal.AllocHGlobal(sizeof(int) * (int)holgenReturnValueHolgenSize);
    Marshal.Copy(holgenResult, 0, holgenReturnValue, (int)holgenReturnValueHolgenSize);
    return holgenReturnValue;
  }
  public abstract string[] SplitName(sbyte delim);
  public static IntPtr SplitNameCaller(IntPtr holgenObject, sbyte delim, out ulong holgenReturnValueHolgenSize)
  {
    var holgenResult = ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SplitName(delim);
    holgenReturnValueHolgenSize = (ulong)holgenResult.Length;
    IntPtr holgenReturnValue = Marshal.AllocHGlobal(IntPtr.Size * (int)holgenReturnValueHolgenSize);
    for (int holgenIterator = 0; holgenIterator < (int)holgenReturnValueHolgenSize; ++holgenIterator)
    {
      IntPtr elemPtr = Marshal.StringToHGlobalAnsi(holgenResult[holgenIterator]);
      Marshal.WriteIntPtr(holgenReturnValue, holgenIterator * IntPtr.Size, elemPtr);
    }
    return holgenReturnValue;
  }
  
  public delegate void ICounterBumperSetNameDelegate(IntPtr holgenObject, string name);
  public delegate string ICounterBumperGetNameDelegate(IntPtr holgenObject);
  public delegate void ICounterBumperBumpDelegate(IntPtr holgenObject);
  public delegate void ICounterBumperSetNameFromCounterDelegate(IntPtr holgenObject, IntPtr ctr);
  public delegate void ICounterBumperSetNameFromRevisionDelegate(IntPtr holgenObject, ref ModuleVersion.Fields version);
  public delegate ModuleVersion.Fields ICounterBumperGetVersionDelegate(IntPtr holgenObject);
  public delegate IntPtr ICounterBumperGetCounterDelegate(IntPtr holgenObject);
  public delegate IntPtr ICounterBumperCloneDelegate(IntPtr holgenObject);
  public delegate void ICounterBumperCopyFromDelegate(IntPtr holgenObject, IntPtr other);
  public delegate void ICounterBumperBumpMultipleDelegate(IntPtr holgenObject, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex=2)] string[] names, ulong namesHolgenSize, [MarshalAs(UnmanagedType.LPArray, SizeParamIndex=4)] uint[] counts, ulong countsHolgenSize);
  public delegate void ICounterBumperSetNameConcatArrayDelegate(IntPtr holgenObject, [MarshalAs(UnmanagedType.LPArray, SizeConst=3)] string[] name);
  public delegate IntPtr ICounterBumperSplitNameAndParseSignedDelegate(IntPtr holgenObject, sbyte delim, out ulong holgenReturnValueHolgenSize);
  public delegate IntPtr ICounterBumperSplitNameDelegate(IntPtr holgenObject, sbyte delim, out ulong holgenReturnValueHolgenSize);
  
  private GCHandle _holgenPtr;
  
}
