// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public abstract class ICounterBumper
{
  public IntPtr HolgenPtr
  {
    get
    {
      if (!_holgenPtr.IsAllocated)
      {
        _holgenPtr = GCHandle.Alloc(this);
      }
      return (IntPtr)_holgenPtr;
    }
  }
  
  public abstract void SetName(string name);
  public static void SetNameCaller(IntPtr holgenObject, string name)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetName(name);
  }
  public abstract void Bump();
  public static void BumpCaller(IntPtr holgenObject)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).Bump();
  }
  public abstract void SetNameFromCounter(Counter ctr);
  public static void SetNameFromCounterCaller(IntPtr holgenObject, IntPtr ctr)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetNameFromCounter(new Counter(ctr));
  }
  public abstract void SetNameFromRevision(ModuleVersion version);
  public static void SetNameFromRevisionCaller(IntPtr holgenObject, ref ModuleVersion.Fields version)
  {
    ((ICounterBumper)GCHandle.FromIntPtr(holgenObject).Target!).SetNameFromRevision(new ModuleVersion{Data = version});
  }
  
  public delegate void ICounterBumperSetNameDelegate(IntPtr holgenObject, string name);
  public delegate void ICounterBumperBumpDelegate(IntPtr holgenObject);
  public delegate void ICounterBumperSetNameFromCounterDelegate(IntPtr holgenObject, IntPtr ctr);
  public delegate void ICounterBumperSetNameFromRevisionDelegate(IntPtr holgenObject, ref ModuleVersion.Fields version);
  
  private GCHandle _holgenPtr;
  
}
