// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public class SingletonCounter
{
  public static uint Get()
  {
    return Marshal.GetDelegateForFunctionPointer<SingletonCounterGetDelegate>(_getImpl)();
  }
  public static void Bump(uint amount)
  {
    Marshal.GetDelegateForFunctionPointer<SingletonCounterBumpDelegate>(_bumpImpl)(amount);
  }
  public static void Reset()
  {
    Marshal.GetDelegateForFunctionPointer<SingletonCounterResetDelegate>(_resetImpl)();
  }
  public static void HolgenInitialize(SingletonCounterGetDelegate singletonCounterGetDelegate, SingletonCounterBumpDelegate singletonCounterBumpDelegate, SingletonCounterResetDelegate singletonCounterResetDelegate)
  {
    _getImpl = Marshal.GetFunctionPointerForDelegate(singletonCounterGetDelegate);
    _bumpImpl = Marshal.GetFunctionPointerForDelegate(singletonCounterBumpDelegate);
    _resetImpl = Marshal.GetFunctionPointerForDelegate(singletonCounterResetDelegate);
  }
  
  public delegate uint SingletonCounterGetDelegate();
  public delegate void SingletonCounterBumpDelegate(uint amount);
  public delegate void SingletonCounterResetDelegate();
  public delegate void SingletonCounterHolgenInitializeDelegate(SingletonCounterGetDelegate singletonCounterGetDelegate, SingletonCounterBumpDelegate singletonCounterBumpDelegate, SingletonCounterResetDelegate singletonCounterResetDelegate);
  
  private static IntPtr _getImpl = IntPtr.Zero;
  private static IntPtr _bumpImpl = IntPtr.Zero;
  private static IntPtr _resetImpl = IntPtr.Zero;
  
}
