// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public class Vector
{
  public Vector(IntPtr ptr)
  {
    HolgenPtr = ptr;
  }
  
  public IntPtr HolgenPtr { get; }
  
  public static void HolgenInitialize()
  {
  }
  
  public delegate void VectorHolgenInitializeDelegate();
  
}
