// This file is generated by holgen. Do not modify manually.

using System.Runtime.InteropServices;

namespace CSharpBindings;

public static class Vector
{
  public static void HolgenInitialize()
  {
  }
  
  public delegate void VectorHolgenInitializeDelegate();
  
}
