// This file is generated by holgen. Do not modify manually.
#pragma once

#include "holgen.h"
namespace holgen_blackbox_test {
template <typename T>
class GlobalPointer {
public:
  static T* GetInstance() {
    return mInstance;
  }
  static void SetInstance(T* ptr) {
    mInstance = ptr;
  }
private:
  inline static T* mInstance = nullptr;
};
}
