-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Armor
---@field id number
---@field armorClass number
Armor = {}

function Armor:Initialize() end
