-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Weapon
---@field id number
---@field damageMin number
---@field damageMax number
Weapon = {}

---@return number
function Weapon:GetAverageDamage() end

function Weapon:Initialize() end

---@return number
function Weapon:GetDamage() end
