-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@alias Race 2|0|1|3
Race = {
  Human = 2,
  Elf = 0,
  Dwarf = 1,
  Hobbit = 3,
  Invalid = 4,
}
