-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class WeaponInInventory
---@field type WeaponType
---@field weapon number[]
WeaponInInventory = {}
