-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class WeaponTypeSword
---@field sharpness number
---@field isShortSword boolean
WeaponTypeSword = {}
