-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class CharacterArmor
---@field dirtAmount number
---@field armorId number
---@field armor Armor
CharacterArmor = {}
