-- This file is generated by holgen. Do not modify manually.
---@diagnostic disable: missing-return
---@class Weapon
---@field id number
---@field name string
---@field damageMin number
---@field damageMax number
Weapon = {}
